### ISSUE TITLE
zoom activation messages still show on streamer mode

### ISSUE THREAD

**Issue by keanureano** [sakura-ryoko/streamer-mode#1]
### Bug description

![image](https://github.com/user-attachments/assets/2c3bbc6b-3a6b-42fc-a96c-71c8de981fdf)

### Steps to reproduce

1. toggle on tweakzoom
2. bind zoom key to c
3. press c

### Expected behavior

the activation messages is hidden

### Actual behavior

the activation messages show up

### Minecraft version

1.21.1

### TemplateMod version

1.0.1

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by sakura-ryoko** [comment]
I knew that I'm going to have to add additional hooks into the mod.  The current version just cancels the default Action Bar messages from Enabling / Disabling a setting.  The Zoom FOV message (Or any other Informational Messages) are handled differently in the code.  I would know, because I coded that message in Tweakeroo with the FOV value.

**Comment by sakura-ryoko** [comment]
My overall goal is to probably add a "Streamer Mode" setting directly in MaLiLib in future versions of the mainstream mod; but this mod will help cover past versions of the mods.

**Comment by keanureano** [comment]
Apologies I should have marked this as a suggestion. Is there an easy way to implement this? If not then it's totally fine, I only use the tweakZoom feature since it works even when I'm freecamming

**Comment by sakura-ryoko** [comment]
v1.0.3 will be able to do this via a new config option.
